"""initial_schema

Revision ID: 5327e82a5ead
Revises:
Create Date: 2026-03-24 16:29:19.223468

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5327e82a5ead"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scan_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("target", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                name="scan_status",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scan_jobs_status"), "scan_jobs", ["status"], unique=False)
    op.create_index(op.f("ix_scan_jobs_target"), "scan_jobs", ["target"], unique=False)
    op.create_table(
        "discovered_assets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column("hostname", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.Text(), nullable=True),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("protocol", sa.String(length=10), nullable=False),
        sa.Column(
            "service_type",
            sa.Enum("TLS", "VPN", "API", name="service_type", create_constraint=True),
            nullable=True,
        ),
        sa.Column("server_software", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["scan_id"], ["scan_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_discovered_assets_scan_id"), "discovered_assets", ["scan_id"], unique=False
    )
    op.create_table(
        "cbom_documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("serial_number", sa.Text(), nullable=False),
        sa.Column("cbom_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["discovered_assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scan_id"], ["scan_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("serial_number"),
    )
    op.create_index(
        op.f("ix_cbom_documents_asset_id"), "cbom_documents", ["asset_id"], unique=False
    )
    op.create_index(op.f("ix_cbom_documents_scan_id"), "cbom_documents", ["scan_id"], unique=False)
    op.create_table(
        "certificate_chains",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column(
            "cert_level",
            sa.Enum("LEAF", "INTERMEDIATE", "ROOT", name="cert_level", create_constraint=True),
            nullable=False,
        ),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("issuer", sa.Text(), nullable=True),
        sa.Column("public_key_algorithm", sa.Text(), nullable=True),
        sa.Column("key_size_bits", sa.Integer(), nullable=True),
        sa.Column("signature_algorithm", sa.Text(), nullable=True),
        sa.Column("quantum_safe", sa.Boolean(), nullable=True),
        sa.Column("not_before", sa.DateTime(timezone=True), nullable=True),
        sa.Column("not_after", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["asset_id"], ["discovered_assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_certificate_chains_asset_id"), "certificate_chains", ["asset_id"], unique=False
    )
    op.create_table(
        "crypto_assessments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("tls_version", sa.Text(), nullable=True),
        sa.Column("cipher_suite", sa.Text(), nullable=True),
        sa.Column("kex_algorithm", sa.Text(), nullable=True),
        sa.Column("auth_algorithm", sa.Text(), nullable=True),
        sa.Column("enc_algorithm", sa.Text(), nullable=True),
        sa.Column("mac_algorithm", sa.Text(), nullable=True),
        sa.Column("kex_vulnerability", sa.Float(), nullable=True),
        sa.Column("sig_vulnerability", sa.Float(), nullable=True),
        sa.Column("sym_vulnerability", sa.Float(), nullable=True),
        sa.Column("tls_vulnerability", sa.Float(), nullable=True),
        sa.Column("risk_score", sa.Float(), nullable=True),
        sa.Column(
            "compliance_tier",
            sa.Enum(
                "FULLY_QUANTUM_SAFE",
                "PQC_TRANSITIONING",
                "QUANTUM_VULNERABLE",
                name="compliance_tier",
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["discovered_assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_crypto_assessments_asset_id"), "crypto_assessments", ["asset_id"], unique=False
    )
    op.create_table(
        "remediation_bundles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("hndl_timeline", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("patch_config", sa.Text(), nullable=True),
        sa.Column("migration_roadmap", sa.Text(), nullable=True),
        sa.Column("source_citations", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["discovered_assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_remediation_bundles_asset_id"), "remediation_bundles", ["asset_id"], unique=False
    )
    op.create_table(
        "compliance_certificates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column(
            "tier",
            sa.Enum(
                "FULLY_QUANTUM_SAFE",
                "PQC_TRANSITIONING",
                "QUANTUM_VULNERABLE",
                name="compliance_tier",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("certificate_pem", sa.Text(), nullable=False),
        sa.Column("signing_algorithm", sa.Text(), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("extensions_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("remediation_bundle_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["asset_id"], ["discovered_assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["remediation_bundle_id"], ["remediation_bundles.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_compliance_certificates_asset_id"),
        "compliance_certificates",
        ["asset_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_compliance_certificates_asset_id"), table_name="compliance_certificates")
    op.drop_table("compliance_certificates")
    op.drop_index(op.f("ix_remediation_bundles_asset_id"), table_name="remediation_bundles")
    op.drop_table("remediation_bundles")
    op.drop_index(op.f("ix_crypto_assessments_asset_id"), table_name="crypto_assessments")
    op.drop_table("crypto_assessments")
    op.drop_index(op.f("ix_certificate_chains_asset_id"), table_name="certificate_chains")
    op.drop_table("certificate_chains")
    op.drop_index(op.f("ix_cbom_documents_scan_id"), table_name="cbom_documents")
    op.drop_index(op.f("ix_cbom_documents_asset_id"), table_name="cbom_documents")
    op.drop_table("cbom_documents")
    op.drop_index(op.f("ix_discovered_assets_scan_id"), table_name="discovered_assets")
    op.drop_table("discovered_assets")
    op.drop_index(op.f("ix_scan_jobs_target"), table_name="scan_jobs")
    op.drop_index(op.f("ix_scan_jobs_status"), table_name="scan_jobs")
    op.drop_table("scan_jobs")
    # ### end Alembic commands ###
