"""auto

Revision ID: 9c81a54a5533
Revises: 5327e82a5ead
Create Date: 2026-04-10 19:00:57.968289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c81a54a5533'
down_revision: Union[str, None] = '5327e82a5ead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_fingerprints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_key', sa.Text(), nullable=False),
    sa.Column('first_seen_scan_id', sa.UUID(), nullable=True),
    sa.Column('last_seen_scan_id', sa.UUID(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('appearance_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('q_score_history', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('latest_q_score', sa.Integer(), nullable=True),
    sa.Column('latest_compliance_tier', sa.Enum('FULLY_QUANTUM_SAFE', 'PQC_TRANSITIONING', 'QUANTUM_VULNERABLE', name='compliance_tier', create_type=False), nullable=True),
    sa.ForeignKeyConstraint(['first_seen_scan_id'], ['scan_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_seen_scan_id'], ['scan_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_key')
    )
    op.create_index(op.f('ix_asset_fingerprints_last_seen_at'), 'asset_fingerprints', ['last_seen_at'], unique=False)
    op.create_table('dns_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('hostname', sa.Text(), nullable=False),
    sa.Column('resolved_ips', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('cnames', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('discovery_source', sa.Text(), nullable=False),
    sa.Column('is_in_scope', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scan_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dns_records_hostname'), 'dns_records', ['hostname'], unique=False)
    op.create_index(op.f('ix_dns_records_scan_id'), 'dns_records', ['scan_id'], unique=False)
    op.create_table('scan_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scan_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_events_scan_id'), 'scan_events', ['scan_id'], unique=False)
    op.create_table('remediation_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('remediation_bundle_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.Enum('P1', 'P2', 'P3', 'P4', name='remediation_priority', create_constraint=True), nullable=False),
    sa.Column('finding', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('effort', sa.Enum('low', 'medium', 'high', name='remediation_effort', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'done', 'verified', name='remediation_status', create_constraint=True), server_default=sa.text("'not_started'"), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('nist_reference', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['discovered_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['remediation_bundle_id'], ['remediation_bundles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediation_actions_asset_id'), 'remediation_actions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_remediation_actions_priority'), 'remediation_actions', ['priority'], unique=False)
    op.create_index(op.f('ix_remediation_actions_status'), 'remediation_actions', ['status'], unique=False)
    op.add_column('discovered_assets', sa.Column('open_ports', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('discovered_assets', sa.Column('asset_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('discovered_assets', sa.Column('is_shadow_it', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('discovered_assets', sa.Column('discovery_source', sa.Text(), nullable=True))
    op.add_column('scan_jobs', sa.Column('scan_profile', sa.Text(), nullable=True))
    op.add_column('scan_jobs', sa.Column('initiated_by', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_jobs', 'initiated_by')
    op.drop_column('scan_jobs', 'scan_profile')
    op.drop_column('discovered_assets', 'discovery_source')
    op.drop_column('discovered_assets', 'is_shadow_it')
    op.drop_column('discovered_assets', 'asset_metadata')
    op.drop_column('discovered_assets', 'open_ports')
    op.drop_index(op.f('ix_remediation_actions_status'), table_name='remediation_actions')
    op.drop_index(op.f('ix_remediation_actions_priority'), table_name='remediation_actions')
    op.drop_index(op.f('ix_remediation_actions_asset_id'), table_name='remediation_actions')
    op.drop_table('remediation_actions')
    op.drop_index(op.f('ix_scan_events_scan_id'), table_name='scan_events')
    op.drop_table('scan_events')
    op.drop_index(op.f('ix_dns_records_scan_id'), table_name='dns_records')
    op.drop_index(op.f('ix_dns_records_hostname'), table_name='dns_records')
    op.drop_table('dns_records')
    op.drop_index(op.f('ix_asset_fingerprints_last_seen_at'), table_name='asset_fingerprints')
    op.drop_table('asset_fingerprints')
    # ### end Alembic commands ###
